- pol/api/v0/person.py
- pol/db/const.py
- tests/app/api_v0/test_persons.py
> fix: PersonType not working 

- pol/api/v0/models.py
- pol/api/v0/person.py
- pol/utils/__init__.py
```diff
+   "images": {
+     "large": "http://lain.bgm.tv/pic/crt/l/a6/e8/1_prsn_ZdFfp.jpg?r=1597241889",
+     "medium": "http://lain.bgm.tv/pic/crt/m/a6/e8/1_prsn_ZdFfp.jpg?r=1597241889",
+     "small": "http://lain.bgm.tv/pic/crt/s/a6/e8/1_prsn_ZdFfp.jpg?r=1597241889",
+     "grid": "http://lain.bgm.tv/pic/crt/g/a6/e8/1_prsn_ZdFfp.jpg?r=1597241889"
+  }
```
> feature(person): add all size of image

- pol/server.py
跨域请求现在由网关处理了，不再由app server进行处理
> refactor: remove cors

- pol/api/v0/__init__.py
- pol/api/v0/character.py
- pol/api/v0/const.py
- pol/api/v0/models.py
- pol/api/v0/person.py
- pol/api/v0/utils.py
- pol/db/const.py
- pol/res.py
- pol/server.py
- tests/app/api_v0/test_character.py
- tests/app/api_v0/test_characters.py
- tests/app/api_v0/test_person.py
虚拟角色API 
#16
绝大多数响应跟与人物api相同，有几个字段不同:
移除了 `last_modified` ，这个字段对应数据库中的 `lastpost`， 意义是最新的用户评论日期，与字段名不符。并非是人物/角色的wiki信息更新日期，也不再允许使用这一条件进行排序。人物api中的这一字段也应该在未来应该进行修复。
移除了人物api中重复的 `img` 字段，提供了 `images` 字段包含所有尺寸的图片。
虚拟角色没有 `career`，所以也删除了这一响应字段和筛选条件。
<details>
<summary>  获取列表 </summary>
GET `/v0/characters`
分页参数 `?limit=30&offset=0` `limit` 最大值 `50`，默认`30`
排序参数 `?sort=id&order=-1` sort 支持 `id` 和 `name`
筛选参数 `?name=`
```json
{
"total": 9,
"limit": 30,
"offset": 0,
"data": [
{
"id": 10,
"name": "Heavy",
"type": 1,
"images": {
"large": "https://lain.bgm.tv/pic/crt/l/10/fb/10_crt_1f1Hz.jpg",
"medium": "https://lain.bgm.tv/pic/crt/m/10/fb/10_crt_1f1Hz.jpg",
"small": "https://lain.bgm.tv/pic/crt/s/10/fb/10_crt_1f1Hz.jpg",
"grid": "https://lain.bgm.tv/pic/crt/g/10/fb/10_crt_1f1Hz.jpg"
},
"locked": …
```
> feat(api): character

- pol/db/const.py
> feat: (revision) type

- pol/api/v0/character.py
- pol/api/v0/episode.py
- pol/api/v0/models/__init__.py
- pol/api/v0/models/base.py
- pol/api/v0/models/subject.py
- pol/api/v0/person.py
```python
class Paged(GenericModel, Generic[T]):
total: int
limit: int
offset: int
data: List[T]
```
`Paged***` -> `Paged[***]`
> refactor: use pydantic generic model

- pol/api/v0/models/subject.py
- pol/api/v0/subject.py
- pol/curd/subject.py
- tests/app/api_v0/test_subject.py
- tests/conftest.py
https://github.com/bangumi/server/issues/42
> feat(subject): tags

- pol/api/v0/character.py
- pol/api/v0/person.py
> fix: person gender zero value

- readme.md
config example doesn't match [`docker-compose.yml` in bangumi/dev-env](https://github.com/bangumi/dev-env/blob/main/docker-compose.yaml#L15-L17)
> doc: update config example

- pol/api/v0/models/__init__.py
- pol/db/const.py
> fix: add missing character role

- pol/api/v0/episode.py
- tests/app/api_v0/test_ep.py
> fix(ep): will not return banned ep

- pol/api/v0/models/subject.py
- pol/api/v0/subject.py
- pol/db/tables.py
close https://github.com/bangumi/api/issues/92
> fix(subject): add missing date

- .dockerignore
- .gitignore
- pol/sa.py
- scripts/public_archive.py
- tests/conftest.py
https://github.com/bangumi/issues/issues/80
> feat: add scripts to dump archive

- pol/api/v0/revision.py
- tests/app/api_v0/test_revision.py
> refactor: remove revisions redis cache

- .github/workflows/ci.yaml
- .github/workflows/lint.yaml
- pol/api/v0/__init__.py
- pol/api/v0/depends/__init__.py
- pol/api/v0/index.py
- pol/api/v0/models/index.py
- pol/db/tables.py
- pol/services/index_service.py
- tests/app/api_v0/test_index.py
- tests/fixtures/mock_db_record.py
- tests/fixtures/mock_service.py
<details>
<summary> 获取目录信息 </summary>
GET `/v0/indices/{index_id}`
响应:
```JSON
{
"id": 15045,
"title": "日本动画最高收视率TOP100",
"desc": "[url]http://www.tudou.com/programs/view/W6eIoxnHs6g/[/url]\r\n有美国动画混入，所以准确的说是在日本播放的动画最高收视率（而且是关东地区的\r\n基本大部分是70年代的，那个年代娱乐贫乏优势真大",
"total": 101,
"stat": {
"comments": 8,
"collects": 96
},
"created_at": "2012-11-08T09:23:16+00:00",
"creator": {
"username": "14127",
"nickname": "nickname 14127"
},
"ban": false
}
```
</details>
close #
<details>
<summary> 获取目录条目 </summary>
GET `/v0/indices/{index_id}/subjects`
request parameters:
type: int
limit: int
offset: int
响应:
```JSON
{
"total": 101,
"limit": 30,
"offset": 0,
"data": [{
"id": 32585,
"type": 2,
"name": "",
"images": null,
"infobox": null,
"date": "2022-01-24",
"comment": "3位 39.4",
"added_at": "2012-11-08T13: …
```
> feat(index): index api

- pol/api/v0/depends/__init__.py
- pol/api/v0/subject.py
- pol/models/subject.py
- pol/services/subject_service.py
- tests/app/api_v0/test_subject_auth.py
- tests/app/services/test_subject_service.py
- tests/fixtures/mock_service.py
fix 500 in `GET https://api.bgm.tv/v0/subjects/293473/characters` (NSFW and LOCKED)
> fix: HTTP 500 on banned subject character

- pol/api/v0/character.py
- pol/api/v0/models/__init__.py
- pol/api/v0/subject.py
- pol/db/tables.py
- pol/models/subject.py
- pol/services/character_service.py
- pol/services/person_service.py
- pol/services/subject_service.py
- tests/app/api_v0/test_character.py
- tests/app/api_v0/test_subject.py
- tests/fixtures/mock_service.py
如果你的 PR 添加了新的 API，请针对每一个 API 填写以下部分
related issue: #88
<details>
<summary> 添加actors字段 </summary>
GET `/v0/subjects/{subject_id}/characters `
Request Query: `subject_id: int`
响应:
```JSON
[
{
"id": 1,
"name": "ルルーシュ・ランペルージ",
"type": 1,
"images": {
"large": "https://lain.bgm.tv/pic/crt/l/7b/3a/1_crt_8V556.jpg?r=1603459589",
"medium": "https://lain.bgm.tv/pic/crt/m/7b/3a/1_crt_8V556.jpg?r=1603459589",
"small": "https://lain.bgm.tv/pic/crt/s/7b/3a/1_crt_8V556.jpg?r=1603459589",
"grid": "https://lain.bgm.tv/pic/crt/g/7b/3a/1_crt_8V556.jpg?r=1603459589"
},
"relation": "主角",
"actors": [
{
"id": 3890,
"name": "person 3890",
"type": 1,
"career": [],
"images": null,
"short_summary": "",
"img": null,
"locked": false
},
{
"id": 3818,
"name": "person 3818",
"type": 1,
"career": [],
"images": null, …
```
> feat(subject): return character related actors

- web/spec.yaml
> docs: update person revision struct

- revision/mysql_repository.go
- revision/mysql_repository_test.go
forget to add `mid == person_id` condition
> fix(revision): search by person id

- domain/revision.go
- mocks/RevisionRepo.go
- model/revision.go
- revision/mysql_repository.go
- revision/mysql_repository_test.go
- web/handler.go
- web/handler/revision.go
- web/handler/revision_test.go
- web/res/revision.go
- web/spec.yaml
rewrite subject revision apis in go
issue: #121
> refactor(revision): subject revision

- model/revision.go
- revision/mysql_repository.go
- revision/mysql_repository_test.go
- web/handler/revision.go
- web/handler/revision_test.go
fix issues in previous pr #133
> fix(revision): problems in previous pr

- .golangci.yaml
- web/handler.go
- web/handler/auth.go
- web/handler/character.go
- web/handler/collection.go
- web/handler/episode.go
- web/handler/index.go
- web/handler/subject.go
- web/handler/user.go
- web/handler/user_test.go
- web/res/error.go
- web/res/user.go
- web/spec.yaml
- web/util/detail.go
GET `/v0/users/{username}`
响应: 与 `/v0/me` 相同
```JSON
{
"avatar": {
"large": "https://lain.bgm.tv/pic/user/l/000/38/29/382951.jpg?r=1571167246",
"medium": "https://lain.bgm.tv/pic/user/m/000/38/29/382951.jpg?r=1571167246",
"small": "https://lain.bgm.tv/pic/user/s/000/38/29/382951.jpg?r=1571167246"
},
"sign": "treeholechan@gmail.com 密码:lovemeplease",
"url": "https://bgm.tv/user/382951",
"username": "382951",
"nickname": "树洞酱",
"id": 382951,
"user_group": 10
}
```
close #
> [Feature]: get user by name

- .gitignore
- domain/revision.go
- mocks/RevisionRepo.go
- model/revision.go
- model/revision.type.go
- pkg/vars/platform.json
- revision/mysql_repository.go
- revision/mysql_repository_test.go
- web/handler.go
- web/handler/revision.go
- web/handler/revision_test.go
- web/res/revision.go
- web/spec.yaml
这是一个 draft pull request
我可以实现 /v0/revisions/characters，现在是否有其他人在做相关工作？
accosiated: #121
> feat(web): API: revisions/characters[/:id]

- web/spec.yaml
operationId is incorrect for get person related characters "/v0/persons/{person_id}/characters":
> Fix incorrect operationId

- character/mysql_repository.go
- character/service.go
- domain/character.go
- internal/cmd/gen/gorm.go
- internal/dal/dao/chii_crt_cast_index.gen.go
- internal/dal/query/chii_crt_cast_index.gen.go
- mocks/CharacterRepo.go
- person/mysql_repository.go
- subject/mysql_repository.go
> fix: get person related characters

- character/mysql_repository.go
- domain/person.go
- mocks/PersonService.go
- person/service.go
> fix: correct character-person relation subject_id

- config/origin.go
- internal/test/request.go
- openapi/private.yaml
- web/handler.go
- web/handler/auth.go
- web/handler/auth_test.go
- web/middleware/origin/new.go
> feature: private logout api

- .github/workflows/lint-other.yaml
- .github/workflows/test-openapi.yaml
- .github/workflows/test.yaml
- Makefile
- domain/user.go
- internal/logger/log/field.go
- internal/test/gorm.go
- mocks/UserRepo.go
- openapi/components/collection_type.yaml
- openapi/components/subject_collection.yaml
- openapi/components/subject_type.yaml
- openapi/test.js
- openapi/v0.yaml
- package.json
- user/mysql_repository.go
- user/mysql_repository_test.go
- web/handler.go
- web/handler/collection.go
- web/handler/collection_test.go
Get single User Collection by subject id 
GET `/v0/users/{username}/collections/{subject_id}`
响应:
```JSON
{
"updated_at": "2022-05-11T11:46:20Z",
"comment": null,
"tags": [],
"subject_id": 372892,
"ep_status": 5,
"vol_status": 0,
"subject_type": 6,
"type": 3,
"rate": 0,
"private": false
}
```
> feature: get single collection by subject_id

- internal/web/handler/character.go
- internal/web/handler/person.go
- internal/web/handler/subject.go
- internal/web/res/image.go
- openapi/v0.yaml
https://github.com/bangumi/server/pull/165
未找到图片时返回默认图片
https://lain.bgm.tv/img/no_icon_subject.png
> feat: redirect to default image when no image

- internal/web/handler.go
- internal/web/handler/character.go
- internal/web/handler/character_test.go
- internal/web/handler/person.go
- internal/web/handler/person_test.go
- internal/web/handler/subject.go
- internal/web/handler/subject_test.go
- internal/web/handler/user.go
- internal/web/handler/user_test.go
- internal/web/res/image.go
- internal/web/res/image_test.go
- internal/web/res/user.go
- internal/web/res/user_test.go
- openapi/v0.yaml
<details>
<summary> 用户头像重定向 </summary>
GET `/v0/users/{username}/avatar`
Request Query: 
- type: 头像图片类型
Response header:
- Location: 图片链接
</details>
close https://github.com/bangumi/server/pull/165#issuecomment-1153045935
> feat: get user avatar handler

- etc/mock.task.yaml
- internal/domain/episode.go
- internal/domain/subject.go
- internal/episode/mysql_repository.go
- internal/mocks/EpisodeRepo.go
- internal/mocks/SubjectService.go
- internal/pkg/generic/slice.go
- internal/subject/service.go
- internal/web/handler/collection.go
- internal/web/handler/collection_test.go
- internal/web/handler/subject.go
- internal/web/res/collection.go
- internal/web/res/subject.go
- openapi/components/subject_collection.yaml
- openapi/components/subject_image.yaml
- openapi/components/subject_v0.yaml
- openapi/components/wiki_v0.yaml
- openapi/v0.yaml
close https://github.com/bangumi/api/issues/141
```diff
{
"updated_at": "2021-12-15T20:00:56+08:00",
"comment": null,
"tags": [],
// 跟 /v0/subjects/{subject_id} 返回的数据相同
+ "subject": {
+  "date": "2004-03-19",
+  "platform": "",
+  ...
+  },
"subject_id": 20,
"vol_status": 0,
"ep_status": 0,
"subject_type": 3,
"type": 3,
"rate": 0,
"private": false
},
```
> feat: attach subject info to subject collection

- internal/domain/episode.go
- internal/episode/mysql_repository.go
- internal/mocks/EpisodeRepo.go
- internal/pkg/generic/slice/slice.go
- internal/pkg/gstr/slice.go
- internal/web/handler/collection.go
- internal/web/handler/collection_test.go
- internal/web/handler/index.go
- internal/web/res/collection.go
- internal/web/res/subject.go
- openapi/components/subject_collection.yaml
- openapi/components/subject_v0.yaml
- openapi/components/subject_v0_slim.yaml
- openapi/v0.yaml
close #https://github.com/bangumi/api/issues/143
> fix!: remove some field from subject collection's embed subject info

- internal/character/mysql_repository.go
- internal/character/mysql_repository_test.go
- internal/ctrl/get_actors.go
- internal/ctrl/get_person_related_subjects.go
- internal/ctrl/get_subject.go
- internal/ctrl/get_subject_related_characters.go
- internal/domain/character.go
- internal/domain/person.go
- internal/domain/subject.go
- internal/mocks/CharacterRepo.go
- internal/mocks/PersonRepo.go
- internal/mocks/SubjectRepo.go
- internal/person/mysql_repository.go
- internal/person/mysql_repository_test.go
- internal/person/service.go
- internal/subject/mysql_repository.go
- internal/subject/mysql_repository_test.go
> refactor: remove variadic from domain interface

- internal/collection/mysql_repo.go
- internal/collection/mysql_repo_test.go
sai老板：忙
close https://github.com/bangumi/api/issues/161
> fix: `chii_ep_status` record is created when needed

- internal/search/handle.go
> fix(search): multiple date filter shoule be `and` condition

- internal/web/handler/comments.go
- internal/web/handler/group_private.go
- internal/web/res/group.go
> fix: return empty group icon url if not set

- internal/search/client.go
- internal/search/index.go
采用 https://github.com/bangumi/server/issues/229 的建议
> search: search result improvement

- internal/domain/revision.go
- internal/mocks/RevisionRepo.go
- internal/model/revision.go
- internal/model/revision.type.go
- internal/revision/mysql_repo_episode.go
- internal/web/handler.go
- internal/web/handler/revision.go
- internal/web/handler/revision_episode.go
- internal/web/res/revision.go
- openapi/v0.yaml
close https://github.com/bangumi/server/issues/121
> feat: episode revision

- web/json.go
- web/new.go
- web/res/error.go
搞笑了，请求的 json 语法错误返回的是 http 500
> fix: reject unknown json field and response code

- ctrl/update_episode_progress.go
- ctrl/update_subject_collection.go
- internal/collections/domain.go
- internal/collections/infra/mysql_repo.go
- internal/collections/infra/mysql_repo_test.go
- internal/mocks/CollectionRepo.go
- web/handler/user/patch_subject_collection.go
- web/handler/user/patch_subject_collection_test.go
- web/handler/user/post_subject_collection_test.go
- web/handler/user/update_episode_collection_test.go
[新增收藏API](https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F/postUserCollection)中，缺少了subject type的写入，会导致收藏列表相关功能获取不到条目
> fix: missing subject collection record subject type

- ctrl/update_subject_collection.go
> fix(collection): update eps

- config/config.go
change it to "timeout"
fix: #480
>  fix(config): duplicate key "key"

- internal/search/extractor.common.go
- internal/search/index.go
- remove summary
- separate name & aliases
> fix: adjust search fields

- internal/search/client.go
> fix: do not index merged subject

- internal/subject/mysql_repository.go
- internal/subject/mysql_repository_test.go
- openapi/v0.yaml
- web/handler/subject/browse.go
* fix argument `sort` for subject browsing
* fix ignore empty rank for browsing sort by rank
* fix nsfw for browsing
> fix: empty rank for subject browsing

- cmd/archive/main.go
Add new fields "date", "favorite" to subject archive.
Add new field "collects", "comments" to person and character archive.
Local test:
subject.jsonlines:
person.jsonlines:
character.jsonlines:
> feat: enrich new fields in archive program

- web/res/image.go
> revert: disable img proxy for person grid image

- internal/user/model.go
- internal/user/mysql_repository.go
- openapi/v0.yaml
- web/handler/user/me.go
仅支持了`/v0/me`下的查询，`/v0/user/{uid}`下鉴于隐私原因未添加条目
Done #689
> feat: support get current user's email and reg_time

- .mockery.yaml
- internal/mocks/TagRepo.go
- internal/pkg/test/web.go
- internal/tag/cache_repo.go
- internal/tag/cache_repo_test.go
- internal/tag/domain.go
- internal/tag/mysql_repo.go
- internal/tag/mysql_repo_test.go
- web/handler/subject/get.go
- web/handler/subject/get_test.go
> fix: duplicated meta tags

- internal/model/person.go
https://github.com/bangumi/api/issues/250
> fix: remove duplicate values
